### PR TITLE
fix: invalid mjs bundle

### LINKED ISSUE #180: Invalid mjs bundle: `contextBridge` shouldn't be imported in `main.mjs`
image

`exposeElectronTRPC` import `contextBridge`, which is not available in main process. This cause a fatal error when users import `electron-trpc/main.mjs` in main process:

image

### PR DESCRIPTION
**Pull request by ylc395**
fix #180

### CODE REVIEW

**Comment by ylc395** [comment]
@jsonnull hello, would you like to help to confirm this PR?

**Comment by ylc395** [comment]
@jsonnull hello, would you check this PR?

**Comment by lucasrabiec** [comment]
BUMP, need it for esm

**Comment by acolvin-h1** [comment]
Can this get pushed? I'm also running into this issue.

**Comment by ylc395** [comment]
@JoeHartzell Hello, Seems like this repo is still active. Would you please check this out?

**Comment by JoeHartzell** [comment]
I can try and take a look at this. Been a bit busy, but this repo is still actively maintained and used by many.

**Comment by jsonnull** [comment]
@ylc395 I have a set of changes coming soon to address issues folks are having using ESM. It's going to be a major version bump in the library, but going forward modules will have test coverage and examples.

In the meantime, you have a few options:
- Use a bundler for your preload file. The electron docs recommend this, and before the changes to support ESM I have not supported using the library for preloads without a bundler. If you're self-imposing this constraint today, that is your decision.
- Hand-write (copy+paste) a preload file. IMO this is the easiest option, and this is safe until the major version bump, at which point you would have to address breaking changes regardless.
- Use pnpm patch or otherwise vendor a version of this library that is modified to your use-case.

**Pull request closed without merging**
